version: "3.7"

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres-rust
    restart: always
    environment:
      - POSTGRES_USER=rust
      - POSTGRES_PASSWORD=rust
      - POSTGRES_DB=open
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data: